export const data: Person[] = [
  {"id":1,"first_name":"Elise","last_name":"Frango","email":"efrango0@naver.com","gender":"Female","age":41,"job":"Data Coordinator","country":"China"},
  {"id":2,"first_name":"Ginnie","last_name":"Arthy","email":"garthy1@dyndns.org","gender":"Female","age":50,"job":"Statistician IV","country":"China"},
  {"id":3,"first_name":"Adair","last_name":"Louiset","email":"alouiset2@mysql.com","gender":"Male","age":84,"job":"Health Coach IV","country":"Tanzania"},
  {"id":4,"first_name":"Dimitri","last_name":"Mabbitt","email":"dmabbitt3@topsy.com","gender":"Male","age":86,"job":"Senior Financial Analyst","country":"Indonesia"},
  {"id":5,"first_name":"Duffie","last_name":"Squibbes","email":"dsquibbes4@irs.gov","gender":"Male","age":41,"job":"Physical Therapy Assistant","country":"Indonesia"},
  {"id":6,"first_name":"Ibrahim","last_name":"Devinn","email":"idevinn5@tuttocitta.it","gender":"Male","age":66,"job":"Assistant Professor","country":"China"},
  {"id":7,"first_name":"Pat","last_name":"Northidge","email":"pnorthidge6@amazon.co.jp","gender":"Female","age":41,"job":"VP Accounting","country":"Vietnam"},
  {"id":8,"first_name":"Sully","last_name":"Pinchbeck","email":"spinchbeck7@apple.com","gender":"Male","age":96,"job":"Teacher","country":"Portugal"},
  {"id":9,"first_name":"Caleb","last_name":"Upstone","email":"cupstone8@shareasale.com","gender":"Bigender","age":89,"job":"VP Accounting","country":"Armenia"},
  {"id":10,"first_name":"Roxi","last_name":"Weighell","email":"rweighell9@jalbum.net","gender":"Female","age":30,"job":"Help Desk Technician","country":"Ivory Coast"},
  {"id":11,"first_name":"Kendricks","last_name":"Dreamer","email":"kdreamera@samsung.com","gender":"Male","age":18,"job":"Business Systems Development Analyst","country":"Venezuela"},
  {"id":12,"first_name":"Bryn","last_name":"Chalcot","email":"bchalcotb@time.com","gender":"Male","age":65,"job":"Analyst Programmer","country":"Russia"},
  {"id":13,"first_name":"Carey","last_name":"Benardeau","email":"cbenardeauc@comsenz.com","gender":"Male","age":88,"job":"Clinical Specialist","country":"Yemen"},
  {"id":14,"first_name":"Fredrick","last_name":"Sawyer","email":"fsawyerd@businessweek.com","gender":"Male","age":89,"job":"Senior Financial Analyst","country":"Yemen"},
  {"id":15,"first_name":"Marylynne","last_name":"Pagen","email":"mpagene@scribd.com","gender":"Female","age":75,"job":"Safety Technician IV","country":"China"},
  {"id":16,"first_name":"Allister","last_name":"Robez","email":"arobezf@phoca.cz","gender":"Male","age":18,"job":"Research Associate","country":"Poland"},
  {"id":17,"first_name":"Sydelle","last_name":"Adamsky","email":"sadamskyg@mapquest.com","gender":"Female","age":54,"job":"Health Coach II","country":"Canada"},
  {"id":18,"first_name":"Filip","last_name":"Boast","email":"fboasth@reddit.com","gender":"Male","age":32,"job":"Computer Systems Analyst III","country":"Peru"},
  {"id":19,"first_name":"Martino","last_name":"Burress","email":"mburressi@nationalgeographic.com","gender":"Male","age":96,"job":"Payment Adjustment Coordinator","country":"Mexico"},
  {"id":20,"first_name":"Ilse","last_name":"Saurin","email":"isaurinj@boston.com","gender":"Female","age":85,"job":"Financial Analyst","country":"Russia"},
  {"id":21,"first_name":"Kipper","last_name":"Grave","email":"kgravek@chronoengine.com","gender":"Male","age":39,"job":"Structural Engineer","country":"China"},
  {"id":22,"first_name":"Conant","last_name":"Lieb","email":"cliebl@springer.com","gender":"Male","age":50,"job":"Accountant I","country":"Indonesia"},
  {"id":23,"first_name":"Pembroke","last_name":"Ellinor","email":"pellinorm@cbslocal.com","gender":"Male","age":72,"job":"Librarian","country":"Russia"},
  {"id":24,"first_name":"Tish","last_name":"Lapides","email":"tlapidesn@prnewswire.com","gender":"Female","age":31,"job":"Design Engineer","country":"China"},
  {"id":25,"first_name":"Ximenes","last_name":"Vedekhin","email":"xvedekhino@prnewswire.com","gender":"Male","age":34,"job":"Marketing Manager","country":"Albania"},
  {"id":26,"first_name":"Gilligan","last_name":"Brahm","email":"gbrahmp@cnn.com","gender":"Female","age":19,"job":"Financial Advisor","country":"China"},
  {"id":27,"first_name":"Cecily","last_name":"Sieghart","email":"csieghartq@yellowpages.com","gender":"Female","age":73,"job":"Statistician IV","country":"Indonesia"},
  {"id":28,"first_name":"Batholomew","last_name":"Markushkin","email":"bmarkushkinr@hubpages.com","gender":"Male","age":82,"job":"Director of Sales","country":"China"},
  {"id":29,"first_name":"Stormy","last_name":"Bradtke","email":"sbradtkes@springer.com","gender":"Female","age":54,"job":"Director of Sales","country":"Ukraine"},
  {"id":30,"first_name":"Vikky","last_name":"Gianotti","email":"vgianottit@gmpg.org","gender":"Female","age":56,"job":"Product Engineer","country":"Kenya"},
  {"id":31,"first_name":"Madelina","last_name":"Hawkslee","email":"mhawksleeu@weather.com","gender":"Female","age":60,"job":"Developer III","country":"Tanzania"},
  {"id":32,"first_name":"Tate","last_name":"De Bernardi","email":"tdebernardiv@jugem.jp","gender":"Male","age":29,"job":"VP Sales","country":"Portugal"},
  {"id":33,"first_name":"Davidson","last_name":"Axell","email":"daxellw@ow.ly","gender":"Male","age":57,"job":"VP Accounting","country":"Armenia"},
  {"id":34,"first_name":"Tallia","last_name":"Airth","email":"tairthx@nhs.uk","gender":"Agender","age":27,"job":"Legal Assistant","country":"Sierra Leone"},
  {"id":35,"first_name":"Konrad","last_name":"Cooney","email":"kcooneyy@myspace.com","gender":"Male","age":51,"job":"VP Accounting","country":"Brazil"},
  {"id":36,"first_name":"Jourdain","last_name":"Cossons","email":"jcossonsz@java.com","gender":"Male","age":26,"job":"Civil Engineer","country":"China"},
  {"id":37,"first_name":"Tudor","last_name":"Fieldhouse","email":"tfieldhouse10@elpais.com","gender":"Male","age":88,"job":"Administrative Officer","country":"Ukraine"},
  {"id":38,"first_name":"Randee","last_name":"Petr","email":"rpetr11@java.com","gender":"Female","age":93,"job":"Senior Editor","country":"Russia"},
  {"id":39,"first_name":"Thomasina","last_name":"Adao","email":"tadao12@weather.com","gender":"Female","age":79,"job":"Safety Technician II","country":"China"},
  {"id":40,"first_name":"Noami","last_name":"Sully","email":"nsully13@nhs.uk","gender":"Female","age":79,"job":"Social Worker","country":"Mongolia"},
  {"id":41,"first_name":"Juana","last_name":"Beaman","email":"jbeaman14@alexa.com","gender":"Female","age":39,"job":"Staff Scientist","country":"Portugal"},
  {"id":42,"first_name":"Leroi","last_name":"Oldland","email":"loldland15@moonfruit.com","gender":"Male","age":19,"job":"Developer I","country":"Indonesia"},
  {"id":43,"first_name":"Hamlen","last_name":"Lightbowne","email":"hlightbowne16@eventbrite.com","gender":"Male","age":89,"job":"Registered Nurse","country":"United States"},
  {"id":44,"first_name":"Chauncey","last_name":"Conan","email":"cconan17@github.com","gender":"Male","age":77,"job":"Design Engineer","country":"Russia"},
  {"id":45,"first_name":"Leeland","last_name":"Damato","email":"ldamato18@quantcast.com","gender":"Male","age":21,"job":"Food Chemist","country":"Brazil"},
  {"id":46,"first_name":"Rowan","last_name":"Espina","email":"respina19@slashdot.org","gender":"Male","age":54,"job":"VP Quality Control","country":"China"},
  {"id":47,"first_name":"Natka","last_name":"Chucks","email":"nchucks1a@earthlink.net","gender":"Female","age":61,"job":"Administrative Officer","country":"Madagascar"},
  {"id":48,"first_name":"Silvio","last_name":"Scurrell","email":"sscurrell1b@reddit.com","gender":"Male","age":37,"job":"Human Resources Assistant III","country":"Brazil"},
  {"id":49,"first_name":"Rudyard","last_name":"Bulled","email":"rbulled1c@friendfeed.com","gender":"Male","age":50,"job":"VP Accounting","country":"Peru"},
  {"id":50,"first_name":"Josh","last_name":"Rigg","email":"jrigg1d@xinhuanet.com","gender":"Male","age":77,"job":"Nuclear Power Engineer","country":"Mauritius"},
  {"id":51,"first_name":"Weylin","last_name":"Adkin","email":"wadkin1e@disqus.com","gender":"Male","age":83,"job":"Analog Circuit Design manager","country":"France"},
  {"id":52,"first_name":"Niko","last_name":"Jowitt","email":"njowitt1f@sourceforge.net","gender":"Polygender","age":92,"job":"Legal Assistant","country":"China"},
  {"id":53,"first_name":"Victor","last_name":"Cratchley","email":"vcratchley1g@storify.com","gender":"Male","age":96,"job":"Physical Therapy Assistant","country":"Colombia"},
  {"id":54,"first_name":"Claiborne","last_name":"Everingham","email":"ceveringham1h@sun.com","gender":"Male","age":89,"job":"Electrical Engineer","country":"Russia"},
  {"id":55,"first_name":"Kaitlyn","last_name":"Parkinson","email":"kparkinson1i@canalblog.com","gender":"Female","age":62,"job":"Budget/Accounting Analyst I","country":"Nigeria"},
  {"id":56,"first_name":"Alexis","last_name":"Lawlance","email":"alawlance1j@chronoengine.com","gender":"Female","age":54,"job":"Web Designer II","country":"Uganda"},
  {"id":57,"first_name":"Carolann","last_name":"Bleesing","email":"cbleesing1k@imgur.com","gender":"Female","age":84,"job":"Web Developer IV","country":"Slovenia"},
  {"id":58,"first_name":"Ricoriki","last_name":"Waulker","email":"rwaulker1l@weebly.com","gender":"Male","age":53,"job":"Social Worker","country":"Russia"},
  {"id":59,"first_name":"Marcie","last_name":"Defew","email":"mdefew1m@nhs.uk","gender":"Female","age":41,"job":"Financial Advisor","country":"Egypt"},
  {"id":60,"first_name":"Addison","last_name":"Pilpovic","email":"apilpovic1n@spotify.com","gender":"Male","age":77,"job":"Developer II","country":"Indonesia"},
  {"id":61,"first_name":"Pauly","last_name":"Jealous","email":"pjealous1o@xing.com","gender":"Female","age":47,"job":"Administrative Assistant IV","country":"China"},
  {"id":62,"first_name":"Mercy","last_name":"Larvent","email":"mlarvent1p@goo.gl","gender":"Non-binary","age":44,"job":"Chief Design Engineer","country":"United States"},
  {"id":63,"first_name":"Alejandro","last_name":"Ennor","email":"aennor1q@purevolume.com","gender":"Male","age":18,"job":"Clinical Specialist","country":"Portugal"},
  {"id":64,"first_name":"Anselma","last_name":"Cantrill","email":"acantrill1r@google.com.br","gender":"Female","age":40,"job":"Nurse Practicioner","country":"Dominican Republic"},
  {"id":65,"first_name":"Veronike","last_name":"Woodroff","email":"vwoodroff1s@virginia.edu","gender":"Female","age":29,"job":"Environmental Tech","country":"Philippines"},
  {"id":66,"first_name":"Lynna","last_name":"Brandli","email":"lbrandli1t@cafepress.com","gender":"Female","age":63,"job":"Environmental Specialist","country":"Czech Republic"},
  {"id":67,"first_name":"Lonny","last_name":"Chesnay","email":"lchesnay1u@symantec.com","gender":"Male","age":71,"job":"Systems Administrator IV","country":"China"},
  {"id":68,"first_name":"Kate","last_name":"Swatland","email":"kswatland1v@bluehost.com","gender":"Female","age":46,"job":"Internal Auditor","country":"Panama"},
  {"id":69,"first_name":"Tanny","last_name":"Memmory","email":"tmemmory1w@yelp.com","gender":"Male","age":27,"job":"Recruiter","country":"Philippines"},
  {"id":70,"first_name":"Lorrayne","last_name":"Cathery","email":"lcathery1x@yahoo.co.jp","gender":"Female","age":70,"job":"Nurse Practicioner","country":"Indonesia"},
  {"id":71,"first_name":"Heall","last_name":"Shelp","email":"hshelp1y@ning.com","gender":"Male","age":80,"job":"Nuclear Power Engineer","country":"Russia"},
  {"id":72,"first_name":"Carrol","last_name":"Ellerman","email":"cellerman1z@odnoklassniki.ru","gender":"Male","age":60,"job":"Administrative Officer","country":"Indonesia"},
  {"id":73,"first_name":"Felix","last_name":"Hynard","email":"fhynard20@nytimes.com","gender":"Male","age":22,"job":"Associate Professor","country":"Indonesia"},
  {"id":74,"first_name":"Amandi","last_name":"Wingar","email":"awingar21@nydailynews.com","gender":"Female","age":50,"job":"Pharmacist","country":"Malaysia"},
  {"id":75,"first_name":"Torrance","last_name":"Merali","email":"tmerali22@whitehouse.gov","gender":"Male","age":25,"job":"Developer IV","country":"Malaysia"},
  {"id":76,"first_name":"Ingrid","last_name":"Drain","email":"idrain23@cnn.com","gender":"Female","age":28,"job":"Developer III","country":"Indonesia"},
  {"id":77,"first_name":"Patrick","last_name":"Vaun","email":"pvaun24@guardian.co.uk","gender":"Male","age":76,"job":"Accountant III","country":"China"},
  {"id":78,"first_name":"Pansy","last_name":"Nibley","email":"pnibley25@imdb.com","gender":"Female","age":66,"job":"Assistant Media Planner","country":"Madagascar"},
  {"id":79,"first_name":"Nicky","last_name":"Cavalier","email":"ncavalier26@alexa.com","gender":"Male","age":38,"job":"Statistician IV","country":"United Kingdom"},
  {"id":80,"first_name":"Beaufort","last_name":"Molson","email":"bmolson27@latimes.com","gender":"Male","age":44,"job":"Registered Nurse","country":"Comoros"},
  {"id":81,"first_name":"Ezequiel","last_name":"Tukely","email":"etukely28@hhs.gov","gender":"Male","age":20,"job":"Registered Nurse","country":"Belarus"},
  {"id":82,"first_name":"Stefano","last_name":"Alliston","email":"salliston29@mac.com","gender":"Male","age":28,"job":"Biostatistician IV","country":"Philippines"},
  {"id":83,"first_name":"Isabelita","last_name":"Agglione","email":"iagglione2a@geocities.jp","gender":"Agender","age":83,"job":"Tax Accountant","country":"France"},
  {"id":84,"first_name":"Beverlie","last_name":"La Vigne","email":"blavigne2b@dagondesign.com","gender":"Female","age":59,"job":"Nurse","country":"Portugal"},
  {"id":85,"first_name":"Aron","last_name":"Lake","email":"alake2c@mozilla.org","gender":"Polygender","age":22,"job":"Nurse","country":"Luxembourg"},
  {"id":86,"first_name":"Creigh","last_name":"Dalloway","email":"cdalloway2d@webnode.com","gender":"Male","age":31,"job":"Occupational Therapist","country":"Russia"},
  {"id":87,"first_name":"Isadore","last_name":"Shakesby","email":"ishakesby2e@nih.gov","gender":"Male","age":75,"job":"Dental Hygienist","country":"Portugal"},
  {"id":88,"first_name":"Curran","last_name":"Blakely","email":"cblakely2f@tripod.com","gender":"Male","age":96,"job":"Actuary","country":"Canada"},
  {"id":89,"first_name":"Diahann","last_name":"Gantzer","email":"dgantzer2g@theatlantic.com","gender":"Female","age":70,"job":"Human Resources Manager","country":"China"},
  {"id":90,"first_name":"Aggi","last_name":"Brauninger","email":"abrauninger2h@liveinternet.ru","gender":"Female","age":38,"job":"Statistician II","country":"Spain"},
  {"id":91,"first_name":"Patti","last_name":"Klainer","email":"pklainer2i@furl.net","gender":"Female","age":88,"job":"Software Consultant","country":"Vietnam"},
  {"id":92,"first_name":"Coral","last_name":"Stainbridge","email":"cstainbridge2j@reddit.com","gender":"Female","age":67,"job":"Chemical Engineer","country":"Serbia"},
  {"id":93,"first_name":"Danette","last_name":"Mcsarry","email":"dmcsarry2k@stanford.edu","gender":"Female","age":85,"job":"Desktop Support Technician","country":"Philippines"},
  {"id":94,"first_name":"Bernadina","last_name":"MacCafferky","email":"bmaccafferky2l@netvibes.com","gender":"Genderqueer","age":96,"job":"Structural Engineer","country":"Kenya"},
  {"id":95,"first_name":"Obie","last_name":"Perillo","email":"operillo2m@hc360.com","gender":"Male","age":44,"job":"Programmer Analyst II","country":"Peru"},
  {"id":96,"first_name":"Amanda","last_name":"Beech","email":"abeech2n@ehow.com","gender":"Female","age":67,"job":"Geologist I","country":"Russia"},
  {"id":97,"first_name":"Meris","last_name":"Trowill","email":"mtrowill2o@technorati.com","gender":"Female","age":80,"job":"Analog Circuit Design manager","country":"Uzbekistan"},
  {"id":98,"first_name":"Issy","last_name":"MacMeeking","email":"imacmeeking2p@arstechnica.com","gender":"Female","age":73,"job":"Junior Executive","country":"Albania"},
  {"id":99,"first_name":"Darlene","last_name":"Blyden","email":"dblyden2q@goodreads.com","gender":"Female","age":39,"job":"Junior Executive","country":"Indonesia"},
  {"id":100,"first_name":"Billie","last_name":"Huriche","email":"bhuriche2r@ucsd.edu","gender":"Male","age":88,"job":"Geologist III","country":"Poland"}
]

export type Gender = 'Male' | 'Female' | 'Non-binary' | 'Genderqueer' | 'Polygender' | 'Bigender' | 'Agender'

export type Person = {
  id: number;
  last_name: string;
  first_name: string;
  gender: Gender;
  email: string;
  age: number;
  job: string;
  country: string
}
